package View;

import Model.DAO.DAOTask;
import Model.State;
import Model.Task;
import Reportes.ReportGenerator;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author jonat
 */
public class homeScreen extends javax.swing.JFrame {
    
    String encabezados[] = {"Tarea ID","Titulo","Descripcion","Fecha limite","Estado de la tarea"};
    DefaultTableModel tlbModel = new DefaultTableModel(encabezados, 0);
    DAOTask DAOtask = new DAOTask();
    CurrentUser currentUser = new CurrentUser();
    ArrayList<Task> taskList = new ArrayList<>();
    Task selectedTask;
    private void SetAnchoColumnas()
    {
         tlbPendingTask.getTableHeader().setResizingAllowed(false);
         setFixedColumnWidth(tlbPendingTask, 0, 70);
         setFixedColumnWidth(tlbPendingTask, 1, 200);
         setFixedColumnWidth(tlbPendingTask, 2, 400);
         setFixedColumnWidth(tlbPendingTask, 3, 130);
         setFixedColumnWidth(tlbPendingTask, 4, 150);
         tlbPendingTask.revalidate();
         tlbPendingTask.repaint();
    }
    private void CargarTabla(String campo)
    {
        selectedTask = null;
        this.taskList = DAOtask.seleccionarDonde(CurrentUser.person.getId_person(), campo);
        this.tlbModel.setNumRows(0);
        for (Task task : taskList) 
        {
        Object[] fila = {
            task.getId_task(),
            task.getTask_name(),
            task.getTask_description(),
            task.getTask_date(),
            task.getState().getState_name()};
         this.tlbModel.addRow(fila);     
        }
        // establecer el modelo de la tabla una vez después de cargar todos los datos
        this.tlbPendingTask.setModel(tlbModel); 
        SetAnchoColumnas();
    }  
    public static void setFixedColumnWidth(JTable table, int columnIndex, int width) 
    {
        TableColumn column = table.getColumnModel().getColumn(columnIndex);
        column.setPreferredWidth(width);
        column.setMinWidth(width);
        column.setMaxWidth(width);
    }
    /**
     * Creates new form homeScreen
     */
    public homeScreen() {
         initComponents();
         SetAnchoColumnas();
         txtCurrentUser.setText(currentUser.GetPerson().getName());
         CargarTabla("Pendiente");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCurrentUser = new javax.swing.JLabel();
        btnEditarTarea = new javax.swing.JButton();
        btnEliminarTarea = new javax.swing.JButton();
        btnAgregarTarea = new javax.swing.JButton();
        btnTareasCompletadas = new javax.swing.JButton();
        btnMarcarTarea = new javax.swing.JButton();
        btnVerPerfil = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tlbPendingTask = new javax.swing.JTable();
        btnTareasPendientes = new javax.swing.JButton();
        btnGenerarRptCompletadas = new javax.swing.JButton();
        btnGenerarRptPendientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(14, 22, 42));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 100));

        txtCurrentUser.setBackground(new java.awt.Color(255, 255, 255));
        txtCurrentUser.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        txtCurrentUser.setForeground(new java.awt.Color(255, 255, 255));
        txtCurrentUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCurrentUser.setText("[Nombre de usuario]");
        txtCurrentUser.setMaximumSize(new java.awt.Dimension(200, 100));

        btnEditarTarea.setBackground(new java.awt.Color(13, 94, 253));
        btnEditarTarea.setText("Editar una Tarea");
        btnEditarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarTareaMouseClicked(evt);
            }
        });
        btnEditarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTareaActionPerformed(evt);
            }
        });

        btnEliminarTarea.setBackground(new java.awt.Color(13, 94, 253));
        btnEliminarTarea.setText("Eliminar una Tarea");
        btnEliminarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarTareaMouseClicked(evt);
            }
        });

        btnAgregarTarea.setBackground(new java.awt.Color(13, 94, 253));
        btnAgregarTarea.setText("Agregar una nueva Tarea");
        btnAgregarTarea.setActionCommand("A");
        btnAgregarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarTareaMouseClicked(evt);
            }
        });

        btnTareasCompletadas.setBackground(new java.awt.Color(13, 94, 253));
        btnTareasCompletadas.setText("Ver Tareas Completadas");
        btnTareasCompletadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTareasCompletadasMouseClicked(evt);
            }
        });

        btnMarcarTarea.setBackground(new java.awt.Color(13, 94, 253));
        btnMarcarTarea.setText("Marcar como completada");
        btnMarcarTarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMarcarTareaMouseClicked(evt);
            }
        });
        btnMarcarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarTareaActionPerformed(evt);
            }
        });

        btnVerPerfil.setBackground(new java.awt.Color(13, 94, 253));
        btnVerPerfil.setText("Ver perfil");
        btnVerPerfil.setActionCommand("A");
        btnVerPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerPerfilMouseClicked(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lista de tareas");

        tlbPendingTask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tlbPendingTask.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tlbPendingTask.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tlbPendingTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tlbPendingTaskMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tlbPendingTask);
        if (tlbPendingTask.getColumnModel().getColumnCount() > 0) {
            tlbPendingTask.getColumnModel().getColumn(0).setResizable(false);
            tlbPendingTask.getColumnModel().getColumn(1).setResizable(false);
            tlbPendingTask.getColumnModel().getColumn(2).setResizable(false);
            tlbPendingTask.getColumnModel().getColumn(3).setResizable(false);
            tlbPendingTask.getColumnModel().getColumn(4).setResizable(false);
        }

        btnTareasPendientes.setBackground(new java.awt.Color(13, 94, 253));
        btnTareasPendientes.setText("Ver Tareas Pendientes");
        btnTareasPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTareasPendientesMouseClicked(evt);
            }
        });

        btnGenerarRptCompletadas.setBackground(new java.awt.Color(13, 94, 253));
        btnGenerarRptCompletadas.setText("Reporte Completadas");
        btnGenerarRptCompletadas.setActionCommand("A");
        btnGenerarRptCompletadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarRptCompletadasMouseClicked(evt);
            }
        });

        btnGenerarRptPendientes.setBackground(new java.awt.Color(13, 94, 253));
        btnGenerarRptPendientes.setText("Reporte Pendientes");
        btnGenerarRptPendientes.setActionCommand("A");
        btnGenerarRptPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarRptPendientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTareasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTareasCompletadas, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMarcarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEliminarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGenerarRptPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarRptCompletadas, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(btnVerPerfil))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(txtCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnVerPerfil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarTarea)
                    .addComponent(btnTareasPendientes)
                    .addComponent(btnEditarTarea)
                    .addComponent(btnGenerarRptCompletadas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcarTarea)
                    .addComponent(btnEliminarTarea)
                    .addComponent(btnTareasCompletadas)
                    .addComponent(btnGenerarRptPendientes))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTareaActionPerformed
    
    }//GEN-LAST:event_btnEditarTareaActionPerformed

    private void btnMarcarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarTareaActionPerformed

    }//GEN-LAST:event_btnMarcarTareaActionPerformed

    private void btnVerPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerPerfilMouseClicked
      userScreen viewUserScreen = new userScreen();
      viewUserScreen.setLocationRelativeTo(null);
      viewUserScreen.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnVerPerfilMouseClicked

    private void btnTareasCompletadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTareasCompletadasMouseClicked
        CargarTabla("Completada");
    }//GEN-LAST:event_btnTareasCompletadasMouseClicked

    private void btnTareasPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTareasPendientesMouseClicked
        CargarTabla("Pendiente");
    }//GEN-LAST:event_btnTareasPendientesMouseClicked

    private void btnEliminarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTareaMouseClicked
        if(selectedTask != null)
        {
        if(JOptionPane.showConfirmDialog(this,"Seguro de eliminar la tarea: "+tlbPendingTask.getValueAt(tlbPendingTask.getSelectedRow(),1).toString(),
                                       "Eliminar Tarea", 
                                       JOptionPane.YES_NO_OPTION,
                                       JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION)
        {   
            if(DAOtask.eliminar(this.selectedTask.getId_task()))
            {
                JOptionPane.showMessageDialog(null, "Tarea eliminada con exito");
                CargarTabla("Pendiente");
            }
            else  {
                JOptionPane.showMessageDialog(null, "Oh no! algo salio mal");
            }     
        }
        }
        else
        {
         JOptionPane.showMessageDialog(null, "Selecciona una tarea");
        }
    }//GEN-LAST:event_btnEliminarTareaMouseClicked

    private void btnAgregarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarTareaMouseClicked
        addTask viewAddTask = new addTask();
        viewAddTask.setLocationRelativeTo(null);
        viewAddTask.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarTareaMouseClicked

    private void btnEditarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarTareaMouseClicked
        if(selectedTask != null)
        {
        editTask viewEditTask = new editTask(this.selectedTask);
        viewEditTask.setLocationRelativeTo(null);
        viewEditTask.setVisible(true);
        this.dispose();
        }
        else
        {
         JOptionPane.showMessageDialog(null, "Selecciona una tarea");
        }
    }//GEN-LAST:event_btnEditarTareaMouseClicked

    private void btnMarcarTareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarcarTareaMouseClicked
       if(selectedTask != null)
       {       
        if(tlbPendingTask.getValueAt(tlbPendingTask.getSelectedRow(),4).toString().equalsIgnoreCase("Completada"))
        {
            JOptionPane.showMessageDialog(null, "La tarea ya fue completada");
            return;
        }
        if(JOptionPane.showConfirmDialog(this,"Seguro de marcar la tarea: "+tlbPendingTask.getValueAt(tlbPendingTask.getSelectedRow(),1).toString()+ " Como completada?",
                                       "Completar Tarea", 
                                       JOptionPane.YES_NO_OPTION,
                                       JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION)
        {   
            
            selectedTask.setState(new State());           
            selectedTask.getState().setId_state(2);
            if(DAOtask.modificar(selectedTask, selectedTask.getId_task()))
            {
                JOptionPane.showMessageDialog(null, "Tarea Completada con exito");
                CargarTabla("Pendiente");
            }
            else  {
                JOptionPane.showMessageDialog(null, "Oh no! algo salio mal");
            }     
        }
       }   
       else
       {
        JOptionPane.showMessageDialog(null, "Selecciona una tarea");
       }
    }//GEN-LAST:event_btnMarcarTareaMouseClicked

    private void tlbPendingTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlbPendingTaskMouseClicked
         this.selectedTask = new Task();
         this.selectedTask.setId_task(Integer.parseInt(tlbPendingTask.getValueAt(tlbPendingTask.getSelectedRow(), 0).toString()));
         this.selectedTask.setTask_name(tlbPendingTask.getValueAt(tlbPendingTask.getSelectedRow(),1).toString());
         this.selectedTask.setTask_description(tlbPendingTask.getValueAt(tlbPendingTask.getSelectedRow(),2).toString());
         this.selectedTask.setTask_date(tlbPendingTask.getValueAt(tlbPendingTask.getSelectedRow(),3).toString());
         this.selectedTask.setState(new State());
         this.selectedTask.getState().setState_name(tlbPendingTask.getValueAt(tlbPendingTask.getSelectedRow(),4).toString());
    }//GEN-LAST:event_tlbPendingTaskMouseClicked

    private void btnGenerarRptCompletadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarRptCompletadasMouseClicked
        ReportGenerator reportGenerator = new ReportGenerator();
        reportGenerator.generarReporteTasks(currentUser.GetPerson().getId_person(), "Completada");
    }//GEN-LAST:event_btnGenerarRptCompletadasMouseClicked

    private void btnGenerarRptPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarRptPendientesMouseClicked
        ReportGenerator reportGenerator = new ReportGenerator();
        reportGenerator.generarReporteTasks(currentUser.GetPerson().getId_person(), "Pendiente");
    }//GEN-LAST:event_btnGenerarRptPendientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTarea;
    private javax.swing.JButton btnEditarTarea;
    private javax.swing.JButton btnEliminarTarea;
    private javax.swing.JButton btnGenerarRptCompletadas;
    private javax.swing.JButton btnGenerarRptPendientes;
    private javax.swing.JButton btnMarcarTarea;
    private javax.swing.JButton btnTareasCompletadas;
    private javax.swing.JButton btnTareasPendientes;
    private javax.swing.JButton btnVerPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tlbPendingTask;
    private javax.swing.JLabel txtCurrentUser;
    // End of variables declaration//GEN-END:variables
}
