package View;

import Model.DAO.DAOPerson;
import Model.DAO.DAOTask;
import java.util.HashSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jonat
 */
public class userScreen extends javax.swing.JFrame {
    CurrentUser currentUser = new CurrentUser();
    DAOPerson DAOperson = new DAOPerson();
    /**
     * Creates new form userScreen
     */
    
    public userScreen() {
        initComponents();
        txtWelcomeUserName.setText(currentUser.GetPerson().getName());
        txtUserName.setText(currentUser.GetPerson().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditarCredencial = new javax.swing.JButton();
        txtWelcomeUserName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNewPass = new javax.swing.JTextField();
        btnCambiarPasswrd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(14, 22, 42));

        btnEditarCredencial.setBackground(new java.awt.Color(13, 94, 253));
        btnEditarCredencial.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCredencial.setText("Actualizar credencial");
        btnEditarCredencial.setActionCommand("Atras");
        btnEditarCredencial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCredencialMouseClicked(evt);
            }
        });

        txtWelcomeUserName.setBackground(new java.awt.Color(255, 255, 255));
        txtWelcomeUserName.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        txtWelcomeUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtWelcomeUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWelcomeUserName.setText("[Nombre de usuario]");
        txtWelcomeUserName.setMaximumSize(new java.awt.Dimension(200, 100));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido");
        jLabel2.setMaximumSize(new java.awt.Dimension(200, 100));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Usuario");

        txtUserName.setBackground(new java.awt.Color(14, 22, 42));
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));

        btnAtras.setBackground(new java.awt.Color(13, 94, 253));
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atras");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");

        txtOldPass.setBackground(new java.awt.Color(14, 22, 42));
        txtOldPass.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nueva Contraeña");

        txtNewPass.setBackground(new java.awt.Color(14, 22, 42));
        txtNewPass.setForeground(new java.awt.Color(255, 255, 255));

        btnCambiarPasswrd.setBackground(new java.awt.Color(13, 94, 253));
        btnCambiarPasswrd.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarPasswrd.setText("Cambiar Contraseña");
        btnCambiarPasswrd.setActionCommand("Atras");
        btnCambiarPasswrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarPasswrdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUserName)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCredencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnCambiarPasswrd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(187, 187, 187))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(txtWelcomeUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWelcomeUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarCredencial))
                .addGap(45, 45, 45)
                .addComponent(btnCambiarPasswrd)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        homeScreen viewHomeScreen = new homeScreen();
        viewHomeScreen.setLocationRelativeTo(null);
        viewHomeScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void btnEditarCredencialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCredencialMouseClicked
        if(!txtUserName.getText().isEmpty())
        {
         if(JOptionPane.showConfirmDialog(this,"Seguro de modificar tu credencial de inicio de sesion a: "+ txtUserName.getText(),
                                       "Modificar Tarea", 
                                       JOptionPane.YES_NO_OPTION,
                                       JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION)             
         {
                      
            if(currentUser.GetPerson().getName().equalsIgnoreCase(txtUserName.getText()))
            {
               JOptionPane.showMessageDialog(null, "Digita una credencial distinta a la acutal");
               return;
            }       
            if(DAOperson.isExist(txtUserName.getText()))
            {
                JOptionPane.showMessageDialog(null, "Ya existe un usuario con esta credencial favor digitar otra");
                return;
            }
            else
            {
                currentUser.GetPerson().setName(txtUserName.getText());
            }
            if(DAOperson.modificar(currentUser.GetPerson(),0))
            {          
                JOptionPane.showMessageDialog(null, "Credencial modificada correctamente");
                currentUser.SetPerson(DAOperson.seleccionarEspecificObject(currentUser.GetPerson().getId_person()));
                txtWelcomeUserName.setText(currentUser.GetPerson().getName());
                txtUserName.setText(currentUser.GetPerson().getName());
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Oh no! algo salio mal");
            }
        }  
         else
         {
           JOptionPane.showMessageDialog(null, "La credencial no puede ser nula");
         }
       }
        
    }//GEN-LAST:event_btnEditarCredencialMouseClicked
    private void limpiar()
    {
       txtOldPass.setText("");
       txtNewPass.setText("");
    }
    private void btnCambiarPasswrdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarPasswrdMouseClicked
        if(!txtNewPass.getText().isEmpty() && !txtOldPass.getText().isEmpty())
        {
            if(!txtOldPass.getText().equals(currentUser.GetPerson().getSecret()))
            {
                JOptionPane.showMessageDialog(null, "La credencial de inicio de sesion ingresada es distinta a la actual");
                limpiar();
                return;
            }
            if(txtNewPass.getText().length() < 4)
            {
               JOptionPane.showMessageDialog(null, "La nueva credencial debe tener 4 caracteres como minimo");        
               return;
            }
            if(txtOldPass.getText().equalsIgnoreCase(txtNewPass.getText()))
            {
                JOptionPane.showMessageDialog(null, "Las nueva credencial debe ser distinta a la actual");
                limpiar();
                return;
            }
            else
            {
            currentUser.GetPerson().setSecret(txtNewPass.getText());
            }
            if(DAOperson.modificar(currentUser.GetPerson(), -1))
            {
                JOptionPane.showMessageDialog(null, "Credencial actualizada correctamente");
                currentUser.SetPerson(DAOperson.seleccionarEspecificObject(currentUser.GetPerson().getId_person()));
                limpiar();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Favor llenar todos los campos");
        }
                    
    }//GEN-LAST:event_btnCambiarPasswrdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCambiarPasswrd;
    private javax.swing.JButton btnEditarCredencial;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtOldPass;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JLabel txtWelcomeUserName;
    // End of variables declaration//GEN-END:variables
}
